import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/" legacyBehavior>
          <a> Home</a>
          </Link>
          <Link href="/events" legacyBehavior>
          <a> Events</a>
          </Link>
          <Link  href="/about-us" legacyBehavior>
          <a> About Us</a>
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} legacyBehavior>
          <a>
            <Image width= {200} height={100} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
          </Link>
        ))}
     
      </main>

      <footer className={styles.footer}>
        <p> © 2023 Time to Code - A Project with Next.JS</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  
  return {
    props: {
      data: events_categories,
    },
  };
}
